export const manufacturers = [
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Maserati",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "MINI",
    "Mitsubishi",
    "Nissan",
    "Porsche",
    "Ram",
    "Rolls-Royce",
    "Subaru",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "Alpina",
    "Bugatti",
    "Citroën",
    "Dacia",
    "Daewoo",
    "Daihatsu",
    "Datsun",
    "Eagle",
    "Fisker",
    "Genesis",
    "Hennessey",
    "Hummer",
    "Isuzu",
    "Lada",
    "Lancia",
    "Lotus",
    "Mahindra",
    "Maybach",
    "Mercury",
    "Morgan",
    "Noble",
    "Opel",
    "Pagani",
    "Perodua",
    "Peugeot",
    "Plymouth",
    "Polestar",
    "Proton",
    "Rimac",
    "Ruf",
    "Saab",
    "Saturn",
    "Scion",
    "Seat",
    "Smart",
    "Spyker",
    "SsangYong",
    "Suzuki",
    "Tatra",
    "Vauxhall",
    "Wiesmann",
    "Zenvo",
    "Abarth",
    "AC Cars",
    "AIWAYS",
    "Allard",
    "Altair",
    "Arrinera",
    "Aspark",
    "Aurora",
    "Axon",
    "BAC",
    "Beauford",
    "Bollinger",
    "Bufori",
    "Caterham",
    "Champion",
    "Changhe",
    "Chery",
    "Czinger",
    "Cupra",
    "Czinger",
    "Dadi",
    "Dallara",
    "Devon",
    "EDAG",
    "Effedi",
    "Eicher",
    "Eagle",
    "Fiat",
    "Faraday Future",
    "Foton",
    "GFG Style",
    "GAC",
    "Gonow",
    "Great Wall",
    "GTA",
    "Haval",
    "Hawtai",
    "Hindustan",
    "Horch",
    "Hotchkiss",
    "Howmet",
    "Hurtan",
    "Ibex",
    "Imperial",
    "Ineos",
    "Innocenti",
    "Isdera",
    "Jedlix",
    "Karlmann",
    "Kawasaki",
    "Kewet",
    "Koenigsegg",
    "KTM",
    "Ladog",
    "Lambretta",
    "Lister",
    "Lucid",
    "Lynk & Co",
    "Magirus",
    "Matra",
    "Melkus",
    "Mitsubishi",
    "Monica",
    "Nimrod",
    "Noble",
    "Nordberg",
    "NSU",
    "Oldsmobile",
    "Oltcit",
    "Opel",
    "Oshkosh",
    "Osprey",
    "Packard",
    "Pegaso",
    "Penton",
    "Peugeot",
    "Pierce-Arrow",
    "Piper",
    "Pontiac",
    "Portaro",
    "Puch",
    "Radical",
    "Railton",
    "Rajango",
    "Red Bull",
    "Rezvani",
    "Rimac",
    "Rinspeed",
    "Rivian",
    "Roewe",
    "Rollin",
    "Ronart",
    "Ronn Motor Company",
    "Rossion",
    "RuF",
    "Scania",
    "SEAT",
    "Secma",
    "Sherp",
    "Sin",
    "Spada",
    "Stutz",
    "Suixing",
    "Superformance",
    "SWM",
    "Talbot",
    "Tazzari",
    "Tecnoidea",
    "Think",
    "Thomas",
    "Tramontana",
    "TVR",
    "Vanderhall",
    "Väth",
    "Vencer",
    "Vespa",
    "VUHL",
    "Westfield",
    "Wuling",
    "YES!",
    "Zenos",
  ];
  

    export const yearsOfProduction = [
    { title: "Year", value: "" },
    { title: "1950", value: "1950" },
    { title: "1951", value: "1951" },
    { title: "1952", value: "1952" },
    { title: "1953", value: "1953" },
    { title: "1954", value: "1954" },
    { title: "1955", value: "1955" },
    { title: "1956", value: "1956" },
    { title: "1957", value: "1957" },
    { title: "1958", value: "1958" },
    { title: "1959", value: "1959" },
    { title: "1960", value: "1960" },
    { title: "1961", value: "1961" },
    { title: "1962", value: "1962" },
    { title: "1963", value: "1963" },
    { title: "1964", value: "1964" },
    { title: "1965", value: "1965" },
    { title: "1966", value: "1966" },
    { title: "1967", value: "1967" },
    { title: "1968", value: "1968" },
    { title: "1969", value: "1969" },
    { title: "1970", value: "1970" },
    { title: "1971", value: "1971" },
    { title: "1972", value: "1972" },
    { title: "1973", value: "1973" },
    { title: "1974", value: "1974" },
    { title: "1975", value: "1975" },
    { title: "1976", value: "1976" },
    { title: "1977", value: "1977" },
    { title: "1978", value: "1978" },
    { title: "1979", value: "1979" },
    { title: "1980", value: "1980" },
    { title: "1981", value: "1981" },
    { title: "1982", value: "1982" },
    { title: "1983", value: "1983" },
    { title: "1984", value: "1984" },
    { title: "1985", value: "1985" },
    { title: "1986", value: "1986" },
    { title: "1987", value: "1987" },
    { title: "1988", value: "1988" },
    { title: "1989", value: "1989" },
    { title: "1990", value: "1990" },
    { title: "1991", value: "1991" },
    { title: "1992", value: "1992" },
    { title: "1993", value: "1993" },
    { title: "1994", value: "1994" },
    { title: "1995", value: "1995" },
    { title: "1996", value: "1996" },
    { title: "1997", value: "1997" },
    { title: "1998", value: "1998" },
    { title: "1999", value: "1999" },
    { title: "2000", value: "2000" },
    { title: "2001", value: "2001" },
    { title: "2002", value: "2002" },
    { title: "2003", value: "2003" },
    { title: "2004", value: "2004" },
    { title: "2005", value: "2005" },
    { title: "2006", value: "2006" },
    { title: "2007", value: "2007" },
    { title: "2008", value: "2008" },
    { title: "2009", value: "2009" },
    { title: "2010", value: "2010" },
    { title: "2011", value: "2011" },
    { title: "2012", value: "2012" },
    { title: "2013", value: "2013" },
    { title: "2014", value: "2014" },
    { title: "2015", value: "2015" },
    { title: "2016", value: "2016" },
    { title: "2017", value: "2017" },
    { title: "2018", value: "2018" },
    { title: "2019", value: "2019" },
    { title: "2020", value: "2020" },
    { title: "2021", value: "2021" },
    { title: "2022", value: "2022" },
    { title: "2023", value: "2023" },
  ];
  
  export const fuels = [
    {
      title: "Fuel",
      value: "",
    },
    {
      title: "Gas",
      value: "Gas",
    },
    {
      title: "Electricity",
      value: "Electricity",
    },
  ];
  
  export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/" },
        { title: "Featured", url: "/" },
        { title: "Partnership", url: "/" },
        { title: "Bussiness Relation", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Socials",
      links: [
        { title: "Discord", url: "/" },
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
  ];